name: Frontend CI

on:

  push:
    # run the pipeline if files inside the frontend dir change ...
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
    build-and-test:
      runs-on:  ubuntu-latest

      # set the default directory for all steps in this job ...
      defaults:
        run:
          working-directory: frontend

      steps:
        # clone the repo onto the GitHub cloud server ...
        - name: Checkout Repository
          uses: actions/checkout@v4
        # set up Node.js environment ...
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '24' # i am using Node version 24 ...
            cache: 'npm'  # caches node_module for faster subsequent runs ...
            cache-dependency-path: ./frontend/package-lock.json  # 
        # install dependencies cleanly ...
        - name: Install Dependencies
          run: npm ci
        # check for code formating/errors ...
        - name: Run Lint
          run: npm lint
        # Run tests ... 
        # - name: Run Tests
        #   run: npm test
        # verify the application builds successfully ...
        - name: Build Application
          run: npm run build
