server:
  port: 8082

spring:
  application:
    name: task-service

  data:
    mongodb:
      database: taskdb

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false

taskflow:
  kafka:
    topics:
      task-status-changed: task.status.changed.v1
      task-completed: task.completed.v1