
# taskflow/backend/config-repo/user-service.yml ...
server:
  port: 8084

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${USER_MONGO_URI}
      database: taskflow-users